### ISSUE TITLE
Deploy all subgraphs to Decentralized Network before June 12

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klima-subgraph#128]
This ticket is for documenting and discussing the move from Hosted Service to the Decentralized Network.
Separate(s) ticket will be created on the Carbonmark and KlimaDAO repos for migrating to the new graph endpoints after they are deployed.

Relevant thread:
https://discord.com/channels/1135827610434289727/1227304858386694174

The following action items have been identified - 

* [ ] Duplicate each subgraph and leverage the Upgrade Indexer
Migration docs:
https://thegraph.com/docs/en/cookbook/upgrading-a-subgraph/
* [ ] Update the CI/CD automation to deploy to both the new and old subgraphs (owned by @0xAurelius )
* [ ] Deploy under the KlimaDAO org (owned by Cujo? Which wallet will own it?)
* [ ] Deploy GRT for signaling
* [ ] Important: Document release, versioning and development process in the Wiki for this klima-subgraph repo
- Versioning: How applications should target stable versions of the graph (guaranteeing no breaking schema changes). Where versions are documented, changelog if possible.
- Development & testing: How devs can develop locally, push, **test** and request review
- Release: How new versions are released and where they can be found. Who is responsible for deployment and signaling. Overview of CI workflow. How we manage GRT balance.

**Comment by jabby09** [comment]
@Atmosfearful @0xAurelius I'll get this added to product sync so it has visibility

1. If we work backwards from June 12 (or say June 5 to have a week of buffer), what is the latest we can start this work and be QA done by June 5?
2. Who owns this and is doing the work or is it multiple resources?

**Comment by 0xAurelius** [comment]
Ideally we should be ready to QA by June 1, so work should start on this around mid-May at the latest

I'm going to take on the new Subgraph creation and CI/CD setup so we can have both upgraded and non-upgraded versions in the interim for testing/fallback, then on June 12th we'll cut over

I will need some assistance from the rest of the team to update any places where we query these subgraphs (for instance, from Bruno on the data-pipelines he built)

**Comment by 0xAurelius** [comment]
Done
