### ISSUE TITLE
Update NBO and UBO to use new Sushi pool after deprecation of Trident

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klima-subgraph#163]
Since Trident is deprecated in Sushi UI, this needs to happen

**Comment by jabby09** [comment]
recommended order of operations would be:
    - remove all PoL liquidity on Sushi Trident (should have minimal impact since there is quite a bit of non-PoL liquidity from C3 gauges)
    - add liquidity to Sushi Legacy (try to get the order right, should be KLIMA/CARBON - NOT CARBON/KLIMA)
    - update retirement aggregator and retirement bonds to reference the new pools
    - update subgraphs to reference new Legacy liquidity pools for prices
    - finally, we can optionally coordinate with C3 to lift the locks on the NBO and UBO liquidity gauges so other users can migrate
