### ISSUE TITLE
Add Toucan Puro Credits

### ISSUE THREAD

**Issue by cujowolf** [KlimaDAO/klima-subgraph#87]
Add support for the Toucan bridged Puro Earth credits

From https://github.com/KlimaDAO/klimadao/issues/1858#issuecomment-1852186005

PuroToucanCarbonOffsets: https://polygonscan.com/address/0x17179596dd44167743f707F590E34C49caBe4E7D#code
PuroToucanCarbonOffsetsFactory: https://polygonscan.com/address/0xc83dc91b3cd45d65f981c0018b3eb1c43a468381#code

**Comment by 0xAurelius** [comment]
Also needs to ensure that Puro tonnes are recorded properly as `activeCredits` in the `polygon-digital-carbon` subgraph so total credit supply reflects them

**Comment by 0xAurelius** [comment]
Also need to update the categorization mapping to include Puro methodologies
